//! 全局快捷键绑定表(`SHORTCUTS`,单一真相)。
//!
//! 06-1 自 `shortcuts.rs` 按职责拆出(纯搬移,零行为变化):
//! 本文件只放**键位 → 命令**绑定表;类型与查表纯函数在父模块,
//! 已实现 ID 清单与命令中文名在 `catalog`,菜单结构在 `menus`。

use egui::Key;

use super::{CtxSet, InputContext, ModMatch, Shortcut, CTX_ALL, CTX_CANVAS, CTX_NO_TEXT};

/// 全局快捷键表(单一真相)。
///
/// 排序无关:同键位多条绑定时按 `ModMatch::specificity` 择优。
pub const SHORTCUTS: &[Shortcut] = &[
    // ── 文件(全局:文本编辑态下仍需可用) ──
    Shortcut {
        id: "file.new",
        key: Key::N,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_ALL,
    },
    Shortcut {
        id: "file.open",
        key: Key::O,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_ALL,
    },
    Shortcut {
        id: "file.save",
        key: Key::S,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_ALL,
    },
    // 02 篇 §四-文件:`Mod+E` = 导出…;`Mod+Shift+E` = 上一导出(快速重复)。
    Shortcut {
        id: "file.export_dialog",
        key: Key::E,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_ALL,
    },
    Shortcut {
        id: "file.export_repeat",
        key: Key::E,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_ALL,
    },
    // ── 编辑(文本编辑态交还输入框自行处理) ──
    Shortcut {
        id: "edit.undo",
        key: Key::Z,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "edit.redo",
        key: Key::Z,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "edit.select_all",
        key: Key::A,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── 对象 ──
    Shortcut {
        id: "object.group",
        key: Key::G,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.ungroup",
        key: Key::G,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.transform_again",
        key: Key::D,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.bring_forward",
        key: Key::CloseBracket,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.bring_to_front",
        key: Key::CloseBracket,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.send_backward",
        key: Key::OpenBracket,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.send_to_back",
        key: Key::OpenBracket,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.delete",
        key: Key::Delete,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.delete",
        key: Key::Backspace,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── 视图(B2:菜单显示的加速键必须真的绑定) ──
    // `+` 在多数键盘上需 Shift+= ,故 shift 取 Any,保证 Ctrl+Shift+= 也能放大。
    Shortcut {
        id: "view.zoom_in",
        key: Key::Plus,
        ctrl: ModMatch::On,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.zoom_in",
        key: Key::Equals,
        ctrl: ModMatch::On,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.zoom_out",
        key: Key::Minus,
        ctrl: ModMatch::On,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.fit",
        key: Key::Num0,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.actual_size",
        key: Key::Num1,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // 07-M 可用性核对补口:design/06 §六「Mod+5 从对象生成参考线」——
    // 命令早已落地但从未绑键(状态提示一直显示"未绑定");与画布右键
    // 菜单、视图菜单同一命令 ID,三入口并行。
    Shortcut {
        id: "view.guides_from_selection",
        key: Key::Num5,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // B3:`Mod+Y` 在 AI 里是轮廓模式,**不是重做**(重做是 Mod+Shift+Z)。
    Shortcut {
        id: "view.outline",
        key: Key::Y,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_grid",
        key: Key::Quote,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_smart_guides",
        key: Key::Semicolon,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // ── 工具箱(02 篇 §三) ──
    Shortcut {
        id: "tool.select",
        key: Key::V,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.rect",
        key: Key::M,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.ellipse",
        key: Key::L,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.hand",
        key: Key::H,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.line",
        key: Key::Backslash,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.pen",
        key: Key::P,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.direct_select",
        key: Key::A,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.text",
        key: Key::T,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // 04-3:Shift+T 在 点/区域 文本间循环(路径文本 v1.5,登记冻结点)
    Shortcut {
        id: "tool.text_cycle_mode",
        key: Key::T,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.eyedropper",
        key: Key::I,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.artboard",
        key: Key::O,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.gradient",
        key: Key::G,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.scissors",
        key: Key::C,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.group_select",
        key: Key::Y,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.zoom",
        key: Key::Z,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── 05-2(X-4 变换工具族,06 篇 §3.10 键位:R / O / S / E)──
    // R/O/S/E 单键此前均无占用(Ctrl 系另有绑定,靠修饰键维度互斥);
    // Shift+O = 画板工具、Ctrl+S = 保存、Ctrl+E = 导出,互不冲突。
    Shortcut {
        id: "tool.rotate",
        key: Key::R,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.mirror",
        key: Key::O,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.scale",
        key: Key::S,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.free_transform",
        key: Key::E,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── 05-2(X-5 铅笔 N,06 篇 §3.7;曲率 Shift+` 按 design/02 §三
    // 「AI 无默认单键,本方案自定义」;度量无标准键位,工具箱/菜单触发)──
    Shortcut {
        id: "tool.pencil",
        key: Key::N,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "tool.curvature",
        key: Key::Backtick,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Off,
        ctx: CTX_CANVAS,
    },
    // ── 05-2(09-C 切片 Shift+K,06 篇 §3.14)──
    Shortcut {
        id: "tool.slice",
        key: Key::K,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── 05-2(09-B 剪切蒙版 Mod+7 / Mod+Alt+7,06 篇 §4.4)──
    Shortcut {
        id: "object.clip_mask",
        key: Key::Num7,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Off,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.release_clip_mask",
        key: Key::Num7,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::On,
        ctx: CTX_CANVAS,
    },
    // ── 画布(方向键微移;Shift = 10px) ──
    Shortcut {
        id: "canvas.nudge_left",
        key: Key::ArrowLeft,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "canvas.nudge_right",
        key: Key::ArrowRight,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "canvas.nudge_up",
        key: Key::ArrowUp,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "canvas.nudge_down",
        key: Key::ArrowDown,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // Esc 在文本编辑态下由文本窗口自行处理(02 篇:文本态仅 Esc / Mod+Enter 生效)。
    Shortcut {
        id: "canvas.cancel",
        key: Key::Escape,
        ctrl: ModMatch::Any,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // P4 钢笔:Enter 结束开放路径
    Shortcut {
        id: "canvas.pen_finish",
        key: Key::Enter,
        ctrl: ModMatch::Off,
        shift: ModMatch::Any,
        alt: ModMatch::Any,
        ctx: CtxSet::one(InputContext::Canvas),
    },
    // ── P3.3 剪贴板(画布上下文;文本框内 Ctrl+C 交给 egui 原生) ──
    Shortcut {
        id: "edit.copy",
        key: Key::C,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "edit.cut",
        key: Key::X,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "edit.paste",
        key: Key::V,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // 贴在前面(AI:Mod+F);Mod+Shift+V 留给垂直居中对齐
    Shortcut {
        id: "edit.paste_in_place",
        key: Key::F,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── P3.8 对齐六快捷键(02 篇 §四,与 AI 完全一致) ──
    Shortcut {
        id: "align.left",
        key: Key::L,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "align.hcenter",
        key: Key::C,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "align.right",
        key: Key::R,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "align.top",
        key: Key::T,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "align.vcenter",
        key: Key::V,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "align.bottom",
        key: Key::B,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // ── P3.9 锁定/隐藏(Mod+2/3;Alt 变体待注册表支持 Alt 维度后补) ──
    Shortcut {
        id: "object.lock",
        key: Key::Num2,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    Shortcut {
        id: "object.hide",
        key: Key::Num3,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_CANVAS,
    },
    // ── P3.2 命令面板 ──
    // ── C3:画板导航 / 面板 Tab ──
    Shortcut {
        id: "view.next_artboard",
        key: Key::PageDown,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.prev_artboard",
        key: Key::PageUp,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.next_panel_tab",
        key: Key::F4,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // ── S1-b 面板显隐(design/02 §四-面板显隐 / design/03 §五) ──
    // F7 = 图层面板(我们的面板坞里切到图层 Tab / 折叠);Tab = 隐藏/恢复所有面板。
    // 两条键位此前均未占用(commands.yaml 无 Tab/F7 绑定),文本编辑态不触发。
    Shortcut {
        id: "view.toggle_layers_panel",
        key: Key::F7,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_all_panels",
        key: Key::Tab,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "app.command_palette",
        key: Key::K,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // ── 04 字符/段落面板(design/03 §5.10;Ctrl+T / Ctrl+Alt+T) ──
    Shortcut {
        id: "view.toggle_char_panel",
        key: Key::T,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Off,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_para_panel",
        key: Key::T,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::On,
        ctx: CTX_NO_TEXT,
    },
    // ── S4 外观/描边面板(design/03 §5.9 / §5.7;⇧F6 / ^F10) ──
    // F6 = 颜色面板(design/03 §5.4,渐变/颜色面板阶段 4 后续入册);
    // ⇧F6 = 外观、^F10 = 描边,均为独立浮窗显隐,文本编辑态不触发。
    Shortcut {
        id: "view.toggle_appearance_panel",
        key: Key::F6,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_stroke_panel",
        key: Key::F10,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // ── S4-b 渐变 / 透明度 / 颜色面板(design/03 §5.6 / §5.8 / §5.4)──
    // ^F9 渐变、⇧^F10 透明度、F6 颜色;均为独立浮窗显隐,文本编辑态不触发。
    // 颜色动作键 X / Shift+X / D 与 AI 一致(纯 X、纯 D 无既有占用)。
    Shortcut {
        id: "view.toggle_gradient_panel",
        key: Key::F9,
        ctrl: ModMatch::On,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_opacity_panel",
        key: Key::F10,
        ctrl: ModMatch::On,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_color_panel",
        key: Key::F6,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "color.toggle_target",
        key: Key::X,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "color.swap_fill_stroke",
        key: Key::X,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "color.default_fill_stroke",
        key: Key::D,
        ctrl: ModMatch::Off,
        shift: ModMatch::Off,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    // ── 阶段 2:变换数值面板(⇧F8)/ 对齐面板(⇧F7)(design/03 §5.2/§5.3)──
    // 两条键位此前均未占用(F7 单键 = 图层、F8 无绑定)。
    Shortcut {
        id: "view.toggle_transform_panel",
        key: Key::F8,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
    Shortcut {
        id: "view.toggle_align_panel",
        key: Key::F7,
        ctrl: ModMatch::Off,
        shift: ModMatch::On,
        alt: ModMatch::Any,
        ctx: CTX_NO_TEXT,
    },
];
