//! 命令目录:已实现命令 ID 清单 + 全部命令的中文名。
//!
//! 06-1 自 `shortcuts.rs` 按职责拆出(纯搬移,零行为变化):
//! 绑定表在 `binds`,菜单结构在 `menus`,本文件只放**命令清单**。

/// 已实现的命令 ID(派发层声明)。必须与 `app.rs::run_command` 的 match 覆盖一致。
pub const IMPLEMENTED_IDS: &[&str] = &[
    "file.new",
    "file.open",
    "file.save",
    "file.export_dialog",
    "file.export_repeat",
    "edit.undo",
    "edit.redo",
    "edit.select_all",
    "object.group",
    "object.ungroup",
    "object.transform_again",
    "object.bring_forward",
    "object.bring_to_front",
    "object.send_backward",
    "object.send_to_back",
    "object.delete",
    "view.zoom_in",
    "view.zoom_out",
    "view.fit",
    "view.actual_size",
    "view.outline",
    "view.toggle_grid",
    "view.toggle_smart_guides",
    "tool.select",
    "tool.rect",
    "tool.ellipse",
    "tool.line",
    "tool.pen",
    "tool.direct_select",
    "tool.zoom",
    "tool.hand",
    "tool.text",
    "tool.eyedropper",
    "tool.artboard",
    "tool.gradient",
    "tool.scissors",
    "tool.group_select",
    // ── 阶段 5(05-2:交互完整性)──
    // X-4 变换工具族
    "tool.rotate",
    "tool.mirror",
    "tool.scale",
    "tool.free_transform",
    // X-5 曲线工具
    "tool.pencil",
    "tool.curvature",
    "edit.pencil_fidelity",
    // 09-C 切片
    "tool.slice",
    "object.slice_from_selection",
    // 09-D 图像置入/替换
    "file.place_image",
    "object.replace_image",
    // 09-E 编辑态辅助
    "view.pixel_preview",
    "tool.measure",
    "canvas.nudge_left",
    "canvas.nudge_right",
    "canvas.nudge_up",
    "canvas.nudge_down",
    "canvas.cancel",
    "canvas.pen_finish",
    // 无键位绑定、仅出现在菜单里的命令
    "view.toggle_theme",
    "object.unlock_all",
    "object.show_all",
    "app.about",
    "app.quit",
    // P3 批次
    "edit.copy",
    "edit.cut",
    "edit.paste",
    "edit.paste_in_place",
    "align.left",
    "align.hcenter",
    "align.right",
    "align.top",
    "align.vcenter",
    "align.bottom",
    "object.lock",
    "object.hide",
    "app.command_palette",
    "object.distribute_h",
    "object.distribute_v",
    "view.toggle_rulers",
    "view.toggle_guides",
    "view.lock_guides",
    "view.guides_from_selection",
    "view.toggle_rulers",
    "view.toggle_guides",
    "view.lock_guides",
    "path.union",
    "path.subtract",
    "path.intersect",
    "path.xor",
    "view.next_artboard",
    "view.prev_artboard",
    "view.next_panel_tab",
    "view.zoom_to_selection",
    // S1-b 面板显隐
    "view.toggle_layers_panel",
    "view.toggle_all_panels",
    // 04 字符/段落面板与文字工具模式循环
    "view.toggle_char_panel",
    "view.toggle_para_panel",
    "tool.text_cycle_mode",
    // S4 外观/描边面板显隐(⇧F6 / ^F10)
    "view.toggle_appearance_panel",
    "view.toggle_stroke_panel",
    // S4-b 渐变/透明度/颜色面板 + 颜色动作(^F9 / ⇧^F10 / F6;X / Shift+X / D)
    "view.toggle_gradient_panel",
    "view.toggle_opacity_panel",
    "view.toggle_color_panel",
    "color.toggle_target",
    "color.swap_fill_stroke",
    "color.default_fill_stroke",
    // ── 阶段 5(AI 规范 9 项菜单;副文档 06)──
    "file.close",
    "file.import_html",
    // ── 阶段 5(05-4-A2:对话框族)──
    // 09-M 文档设置 / 09-N 外部冲突三方对比 / X-7 打印 / 09-L 首选项与键位编辑器
    // / 09-O 字体缺失 / X-7 新建工作区
    "file.doc_settings",
    "file.resolve_conflict",
    "file.print",
    "edit.preferences",
    "edit.keyboard_shortcuts",
    "object.clip_mask",
    "object.release_clip_mask",
    "object.outline_stroke",
    "text.upper_case",
    "text.lower_case",
    "text.create_outlines",
    "text.find_font",
    "select.inverse",
    "select.next_object",
    "select.prev_object",
    "select.same_fill",
    "select.same_stroke",
    "select.same_stroke_width",
    "select.all_text",
    "select.all_locked",
    "select.all_hidden",
    "effect.repeat_last",
    "effect.drop_shadow",
    "effect.inner_shadow",
    "effect.outer_glow",
    "effect.inner_glow",
    "effect.round_corners",
    "effect.gaussian_blur",
    "effect.feather",
    "effect.distort",
    "view.hide_edges",
    "view.browser_proof",
    "window.workspace_basic",
    "window.workspace_type",
    "window.workspace_export",
    "window.new_workspace",
    "window.tab_properties",
    "window.tab_layers",
    "window.tab_artboards",
    "window.tab_tokens",
    "help.shortcuts",
    "help.check_update",
    "help.capabilities",
    // 阶段 6(工具箱四向停靠 + 单双列;副文档 07)
    "view.dock_toolbar_top",
    "view.dock_toolbar_left",
    "view.dock_toolbar_right",
    "view.dock_toolbar_bottom",
    "view.toolbar_columns_1",
    "view.toolbar_columns_2",
    // ── 阶段 2(副文档 03:路径查找器扩展 / 变换 / 对齐)──
    "path.merge",
    "path.subtract_back",
    "path.crop",
    // ── 阶段 5(05-3 / X-1:路径查找器多结果三运算)──
    "path.divide",
    "path.trim",
    "path.outline",
    "view.toggle_transform_panel",
    "view.toggle_align_panel",
    "align.to_selection",
    "align.to_key_object",
    "align.to_artboard",
    "object.distribute_hspace",
    "object.distribute_vspace",
    // ── 阶段 2(副文档 02:启动主页与多窗口)──
    // 项目窗口侧:回主页 / 关闭窗口(关闭确认在 ShellApp)
    "file.home",
    // 主页动作(02-3 / 02-4:主页所有操作都有命令 ID,Agent 可复现)
    "home.new_project",
    "home.open_project",
    "home.new_from_template",
    "home.open_selected",
    "home.remove_selected",
    "home.select_next",
    "home.select_prev",
    "home.pin_selected",
    "home.search",
    "home.restore_session",
    "home.capabilities",
    // ── 04-4(副文档 04:调试 HUD 与状态栏)──
    "view.developer_stats",
    "view.toggle_hints",
    // ── 第四轮 H-1(UI 手感):动效总开关 ──
    "view.toggle_motion",
    // ── 04-3(副文档 04:UI 缩放档位;完整首选项属阶段 5)──
    "view.ui_scale_up",
    "view.ui_scale_down",
    "view.ui_scale_reset",
    // ── 04-6(副文档 04:design/06 §二「显示未支持工具」开关)──
    "edit.toggle_unsupported_tools",
    // ── 阶段 7(数据安全批次:07-A 自动保存 / 07-D 历史 / 07-E 体检)──
    "edit.autosave_interval",
    "view.toggle_history_panel",
    "file.health_check",
    // ── 阶段 7b(编辑体验批次:07-K 资产面板)──
    "view.toggle_assets_panel",
    // ── 阶段 5(05-5:断点与伪类闭环)──
    "view.breakpoint_cycle",
    "style.state_toggle",
    // ── 阶段 5(05-8:符号 / 组件,09-H;ADR-VB-L10)──
    "object.symbol_create",
    "object.symbol_detach",
    "object.symbol_reset_overrides",
    "object.symbol_swap_main",
    "object.symbol_select_instances",
    // ── 阶段 5(05-9:动效时间轴,09-I;ADR-VB-L11)──
    "view.toggle_timeline_panel",
    "anim.play_toggle",
    "anim.stop",
    "anim.loop_toggle",
    "anim.keyframe_add",
    "anim.keyframe_delete",
    "anim.clear",
    // ── 阶段 5(05-10:插件系统,09-J;ADR-VB-L12)──
    "edit.plugins",
    "view.toggle_plugins_panel",
];

/// 全部命令的中文名(命令面板 / 菜单 / 状态提示共用)。
pub const CMD_LABELS: &[(&str, &str)] = &[
    ("file.new", "新建项目…(对话框,新窗口打开)"),
    ("file.open", "打开项目…"),
    ("file.save", "保存"),
    ("file.export_dialog", "导出…"),
    ("file.export_repeat", "上次导出(当前画板 PNG @2x)"),
    ("app.quit", "退出"),
    ("edit.undo", "撤销"),
    ("edit.redo", "重做"),
    ("edit.select_all", "全选(当前画板)"),
    ("edit.copy", "复制"),
    ("edit.cut", "剪切"),
    ("edit.paste", "粘贴"),
    ("edit.paste_in_place", "贴在前面(就地)"),
    ("object.group", "编组"),
    ("object.ungroup", "取消编组"),
    ("object.transform_again", "再次变换"),
    ("object.bring_forward", "前移一层"),
    ("object.bring_to_front", "置于顶层"),
    ("object.send_backward", "后移一层"),
    ("object.send_to_back", "置于底层"),
    ("object.delete", "删除对象"),
    ("object.lock", "锁定所选"),
    ("object.unlock_all", "解锁全部"),
    ("object.hide", "隐藏所选"),
    ("object.show_all", "显示全部"),
    ("align.left", "水平左对齐"),
    ("align.hcenter", "水平居中对齐"),
    ("align.right", "水平右对齐"),
    ("align.top", "垂直顶对齐"),
    ("align.vcenter", "垂直居中对齐"),
    ("align.bottom", "垂直底对齐"),
    ("path.union", "路径查找器:联集"),
    ("path.subtract", "路径查找器:减去顶层"),
    ("path.intersect", "路径查找器:交集"),
    ("path.xor", "路径查找器:差集"),
    ("object.distribute_h", "水平等距分布"),
    ("object.distribute_v", "垂直等距分布"),
    ("view.zoom_in", "放大"),
    ("view.zoom_out", "缩小"),
    ("view.fit", "适合窗口"),
    ("view.actual_size", "实际大小 100%"),
    ("view.outline", "轮廓模式(线框)"),
    ("view.toggle_grid", "显示 / 隐藏网格"),
    ("view.toggle_smart_guides", "智能参考线开关"),
    ("view.toggle_theme", "深色 / 浅色主题"),
    ("tool.select", "选择工具"),
    ("tool.rect", "矩形工具"),
    ("tool.ellipse", "椭圆工具"),
    ("tool.line", "直线工具"),
    ("tool.pen", "钢笔工具"),
    ("tool.direct_select", "直接选择工具"),
    ("tool.zoom", "缩放工具"),
    ("tool.hand", "抓手工具"),
    ("tool.text", "文字工具"),
    ("tool.eyedropper", "吸管工具"),
    ("tool.artboard", "画板工具"),
    ("tool.gradient", "渐变工具"),
    ("tool.scissors", "剪刀工具"),
    ("tool.group_select", "编组选择工具"),
    // ── 阶段 5(05-2:交互完整性)──
    ("tool.rotate", "旋转工具(单击设中心,拖拽旋转;Shift 15°)"),
    ("tool.mirror", "镜像工具(单击设中心,拖动定镜像轴)"),
    ("tool.scale", "缩放工具(单击设中心,拖拽缩放;Shift 等比)"),
    ("tool.free_transform", "自由变换工具(拖选区四角,对角锚定)"),
    ("tool.pencil", "铅笔工具(自由绘制,按保真度抽稀为路径)"),
    ("tool.curvature", "曲率工具(点击矢量路径自动拟合平滑控制点)"),
    ("edit.pencil_fidelity", "设置 → 铅笔保真度(档位循环 1–16px)"),
    (
        "tool.slice",
        "切片工具(Shift+K 拖框建立 data-vb-slice 切片)",
    ),
    ("object.slice_from_selection", "切片 → 从选区建立"),
    (
        "file.place_image",
        "置入图像…(选文件入 assets/,选中设 src 或新建 img)",
    ),
    (
        "object.replace_image",
        "替换图像…(保持几何,SetImageSrc 可撤销)",
    ),
    ("view.pixel_preview", "像素预览(缩放 ≥8× 对齐物理像素网格)"),
    ("tool.measure", "度量工具(拖动量距,单击标注对象尺寸)"),
    ("canvas.cancel", "取消 / 清空选区"),
    ("canvas.pen_finish", "钢笔:结束路径"),
    ("canvas.nudge_left", "微移左 1px"),
    ("canvas.nudge_right", "微移右 1px"),
    ("canvas.nudge_up", "微移上 1px"),
    ("canvas.nudge_down", "微移下 1px"),
    ("view.toggle_rulers", "显示 / 隐藏标尺"),
    ("view.toggle_guides", "显示 / 隐藏参考线"),
    ("view.lock_guides", "锁定参考线"),
    ("view.guides_from_selection", "从选区生成参考线"),
    ("app.command_palette", "命令面板"),
    ("view.next_artboard", "下一画板"),
    ("view.prev_artboard", "上一画板"),
    ("view.next_panel_tab", "切换右侧面板 Tab"),
    ("view.zoom_to_selection", "缩放到选区"),
    ("app.about", "关于"),
    // S1-b 面板显隐
    ("view.toggle_layers_panel", "图层面板显隐"),
    ("view.toggle_all_panels", "隐藏 / 恢复所有面板"),
    // 04 字符/段落面板
    ("view.toggle_char_panel", "字符面板显隐"),
    ("view.toggle_para_panel", "段落面板显隐"),
    ("tool.text_cycle_mode", "文字工具:点/区域循环"),
    // S4 外观/描边面板(design/03 §5.9 / §5.7)
    ("view.toggle_appearance_panel", "外观面板显隐"),
    ("view.toggle_stroke_panel", "描边面板显隐"),
    // S4-b 渐变/透明度/颜色(design/03 §5.6 / §5.8 / §5.4)
    ("view.toggle_gradient_panel", "渐变面板显隐"),
    ("view.toggle_opacity_panel", "透明度面板显隐"),
    ("view.toggle_color_panel", "颜色面板显隐"),
    ("color.toggle_target", "颜色:切换填充/描边"),
    ("color.swap_fill_stroke", "颜色:交换填充与描边"),
    ("color.default_fill_stroke", "颜色:恢复默认填色/描边色"),
    // 阶段 5(AI 规范 9 项菜单;副文档 06)
    ("file.close", "关闭窗口(文档)"),
    ("file.import_html", "导入 HTML…"),
    // ── 阶段 5(05-4-A2:对话框族)──
    (
        "file.doc_settings",
        "文档设置…(项目名/输出模式/网格与参考线,应用后生效)",
    ),
    (
        "file.resolve_conflict",
        "对比并合并…(外部改动三方对比:磁盘/内存/自动快照)",
    ),
    ("file.print", "打印…(当前画板 → 临时 PDF → 系统程序打开)"),
    ("edit.preferences", "首选项…(九分类;改动即时生效)"),
    (
        "edit.keyboard_shortcuts",
        "键盘快捷键…(键位方案编辑器,方案存 keymap.json)",
    ),
    ("object.clip_mask", "建立剪切蒙版"),
    ("object.release_clip_mask", "释放剪切蒙版"),
    ("object.outline_stroke", "轮廓化描边"),
    ("text.upper_case", "更改大小写 → 大写"),
    ("text.lower_case", "更改大小写 → 小写"),
    ("text.create_outlines", "创建轮廓"),
    ("text.find_font", "查找字体…(缺失字体检测与替换,可撤销)"),
    ("select.inverse", "选择反向"),
    ("select.next_object", "选择上方的下一个对象"),
    ("select.prev_object", "选择下方的下一个对象"),
    ("select.same_fill", "选择相同填充色"),
    ("select.same_stroke", "选择相同描边色"),
    ("select.same_stroke_width", "选择相同描边粗细"),
    ("select.all_text", "选择全部文本对象"),
    ("select.all_locked", "选择所有锁定对象"),
    ("select.all_hidden", "选择所有隐藏对象"),
    ("effect.repeat_last", "应用上一个效果"),
    ("effect.drop_shadow", "效果:投影"),
    ("effect.inner_shadow", "效果:内阴影"),
    ("effect.outer_glow", "效果:外发光"),
    ("effect.inner_glow", "效果:内发光"),
    ("effect.round_corners", "效果:圆角"),
    ("effect.gaussian_blur", "效果:高斯模糊"),
    ("effect.feather", "效果:羽化"),
    ("effect.distort", "扭曲和变换…"),
    ("view.hide_edges", "隐藏边缘"),
    ("view.browser_proof", "浏览器校对…"),
    ("window.workspace_basic", "工作区:基本功能"),
    ("window.workspace_type", "工作区:排版"),
    ("window.workspace_export", "工作区:导出"),
    (
        "window.new_workspace",
        "新建工作区…(保存当前布局为命名预设,可切换/删除)",
    ),
    ("window.tab_properties", "面板坞:属性"),
    ("window.tab_layers", "面板坞:图层"),
    ("window.tab_artboards", "面板坞:画板"),
    ("window.tab_tokens", "面板坞:令牌"),
    ("help.shortcuts", "键位速查表…"),
    ("help.check_update", "检查更新…"),
    ("help.capabilities", "能力台账(做了什么/没做什么)"),
    // 阶段 6(工具箱四向停靠 + 单双列)
    ("view.dock_toolbar_top", "工具箱:停靠到顶部"),
    ("view.dock_toolbar_left", "工具箱:停靠到左侧"),
    ("view.dock_toolbar_right", "工具箱:停靠到右侧"),
    ("view.dock_toolbar_bottom", "工具箱:停靠到底部"),
    ("view.toolbar_columns_1", "工具箱:单列"),
    ("view.toolbar_columns_2", "工具箱:双列"),
    // 阶段 2(副文档 03)
    ("path.merge", "路径查找器:合并"),
    ("path.subtract_back", "路径查找器:减去后方对象"),
    ("path.crop", "路径查找器:裁剪"),
    // ── 阶段 5(05-3 / X-1:路径查找器多结果三运算)──
    ("path.divide", "路径查找器:分割"),
    ("path.trim", "路径查找器:修边"),
    ("path.outline", "路径查找器:轮廓"),
    ("view.toggle_transform_panel", "变换面板显隐"),
    ("view.toggle_align_panel", "对齐面板显隐"),
    ("align.to_selection", "对齐到:选区"),
    ("align.to_key_object", "对齐到:关键对象"),
    ("align.to_artboard", "对齐到:画板"),
    ("object.distribute_hspace", "水平等间隙分布"),
    ("object.distribute_vspace", "垂直等间隙分布"),
    // 阶段 2(副文档 02:启动主页与多窗口)
    ("file.home", "主页…(打开主页窗口)"),
    ("home.new_project", "主页:新建项目"),
    ("home.open_project", "主页:打开项目…"),
    ("home.new_from_template", "主页:从模板新建"),
    ("home.open_selected", "主页:打开选中的最近项目"),
    ("home.remove_selected", "主页:移除选中的最近记录"),
    ("home.select_next", "主页:选中下一项"),
    ("home.select_prev", "主页:选中上一项"),
    ("home.pin_selected", "主页:固定/取消固定选中项"),
    ("home.search", "主页:搜索过滤最近项目"),
    ("home.restore_session", "主页:恢复上次会话"),
    ("home.capabilities", "主页:能力台账"),
    // ── 04-4(副文档 04:调试 HUD 与状态栏)──
    ("view.developer_stats", "开发者统计(调试数据默认隐藏)"),
    ("view.toggle_hints", "提示条(操作提示/入门教学,可关)"),
    (
        "view.toggle_motion",
        "界面动效(淡入/过渡,可关;首选项「常规」同款开关)",
    ),
    // ── 04-3(副文档 04:UI 缩放档位)──
    ("view.ui_scale_up", "界面缩放:增大一档"),
    ("view.ui_scale_down", "界面缩放:减小一档"),
    ("view.ui_scale_reset", "界面缩放:复位 100%"),
    // ── 04-6(副文档 04:design/06 §二 未支持工具开关)──
    ("edit.toggle_unsupported_tools", "工具 → 显示未支持工具"),
    // ── 阶段 7(数据安全批次:07-A 自动保存 / 07-D 历史 / 07-E 体检)──
    (
        "edit.autosave_interval",
        "设置 → 自动保存间隔(关/30/60/120/300 档位循环)",
    ),
    ("view.toggle_history_panel", "历史面板显隐(撤销历史可跳转)"),
    ("file.health_check", "项目健康检查…"),
    // ── 阶段 7b(编辑体验批次:07-K 资产面板)──
    (
        "view.toggle_assets_panel",
        "资产面板显隐(assets/ 清单 + 引用关系 + 定位/替换)",
    ),
    // ── 阶段 5(05-5:断点与伪类闭环)──
    ("view.breakpoint_cycle", "断点预览:循环切换(默认 → 各断点)"),
    ("style.state_toggle", "属性面板状态:正常 / 悬停(hover)"),
    // ── 阶段 5(05-8:符号 / 组件,09-H)──
    (
        "object.symbol_create",
        "创建组件(选中提升为主件,当前位置变为首个实例)",
    ),
    (
        "object.symbol_detach",
        "分离实例(实例转普通元素,不再随主件同步)",
    ),
    (
        "object.symbol_reset_overrides",
        "重置覆盖(实例还原为主件当前内容)",
    ),
    (
        "object.symbol_swap_main",
        "替换主件定义(以实例当前内容为新定义并同步其余实例)",
    ),
    ("object.symbol_select_instances", "选择所有实例(同主件)"),
    // ── 阶段 5(05-9:动效时间轴,09-I;ADR-VB-L11)──
    (
        "view.toggle_timeline_panel",
        "时间轴面板(关键帧轨道 + 播放预览)",
    ),
    ("anim.play_toggle", "动画预览:播放 / 暂停"),
    ("anim.stop", "动画预览:停止并回零"),
    ("anim.loop_toggle", "动画预览:循环开 / 关"),
    (
        "anim.keyframe_add",
        "在播放头处加关键帧(选中对象;值取静态值)",
    ),
    ("anim.keyframe_delete", "删除选中的关键帧"),
    ("anim.clear", "清除对象动画(移除 @keyframes 与 animation)"),
    // ── 阶段 5(05-10:插件系统,09-J;ADR-VB-L12)──
    (
        "edit.plugins",
        "插件管理…(安装/授权/启停/日志/重启;插件 = 外部进程,默认零权限)",
    ),
    (
        "view.toggle_plugins_panel",
        "插件面板显隐(Running 插件的注册面板,受控 UI)",
    ),
];
